// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy13FonsZyH5CGeAKnsvIuU1eksgpMvFw',
    appId: '1:716076424963:web:8335bd0be3e2ddb1ee9336',
    messagingSenderId: '716076424963',
    projectId: 'labtest-21da2',
    authDomain: 'labtest-21da2.firebaseapp.com',
    storageBucket: 'labtest-21da2.appspot.com',
    measurementId: 'G-6GFZ0WRNN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY6ZRGLF7_78ZMjWvnG_nAOuVd7HLUJw4',
    appId: '1:716076424963:android:36bb043b053011b9ee9336',
    messagingSenderId: '716076424963',
    projectId: 'labtest-21da2',
    storageBucket: 'labtest-21da2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiyfDk86140JFEuvcI9Ye6lDny15Z82fc',
    appId: '1:716076424963:ios:9953b811d7254d6bee9336',
    messagingSenderId: '716076424963',
    projectId: 'labtest-21da2',
    storageBucket: 'labtest-21da2.appspot.com',
    iosClientId: '716076424963-oqib3l1525sj6m3n0advr5k388p69ni1.apps.googleusercontent.com',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiyfDk86140JFEuvcI9Ye6lDny15Z82fc',
    appId: '1:716076424963:ios:9953b811d7254d6bee9336',
    messagingSenderId: '716076424963',
    projectId: 'labtest-21da2',
    storageBucket: 'labtest-21da2.appspot.com',
    iosClientId: '716076424963-oqib3l1525sj6m3n0advr5k388p69ni1.apps.googleusercontent.com',
    iosBundleId: 'com.example.labtest',
  );
}
